apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipping-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-db
  template:
    metadata:
      labels:
        app: shipping-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: shipping_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shipping-secret
                  key: db_password
          volumeMounts:
            - name: shipping-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: shipping-db-storage
          persistentVolumeClaim:
            claimName: shipping-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-db
spec:
  selector:
    app: shipping-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
